version: '3'
services:
    back-service:
        build: ./back
        ports:
        - 8080:8080

    front-service:
        build: ./front
        ports:
        - 80:80
        depends_on:
        - back-service
